package tooling

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// SkillSnapshotConfig declares how to build a bundled, self-contained
// documentation snapshot for a skill package: which docs/core/<locale>/
// files to concatenate, in which locales, and where to write the result.
type SkillSnapshotConfig struct {
	OutputPath string   // repo-relative, e.g. skills/specialist/references/rgb-system.md
	Inputs     []string // repo-relative to docs/core/<locale>/, in concatenation order
	Locales    []string // outer loop is Inputs, inner loop is Locales — see GenerateSkillSnapshot
}

const skillSnapshotHeader = "# RGB System — Canonical Rules (bundled snapshot)\n" +
	"\n" +
	"This file is a verbatim, bundled copy of the RGB System canonical\n" +
	"documentation, generated for the `rgb-specialist` skill so the\n" +
	"package is self-contained when copied outside this repository.\n" +
	"\n" +
	"**Source of truth**: `docs/core/` in the\n" +
	"[rpg-system-rgb](https://github.com/SergioLacerda/rpg-system-rgb) repository\n" +
	"(see ADR-002 and ADR-014). If this file and `docs/core/` ever disagree,\n" +
	"`docs/core/` wins — this file is regenerated by `make generate`, not\n" +
	"hand-maintained (see ADR-014).\n" +
	"\n" +
	"---\n" +
	"\n"

// GenerateSkillSnapshot concatenates cfg.Inputs x cfg.Locales from
// docs/core/<locale>/<input> (relative to repoRoot) into cfg.OutputPath,
// each section preceded by a `<!-- Source: ... -->` comment and separated
// by a `---` rule, reproducing the format this snapshot has carried since
// it was first hand-authored (ADR-014). It never partially writes the
// output: any read failure aborts before anything is written.
func GenerateSkillSnapshot(repoRoot string, cfg SkillSnapshotConfig) error {
	var buf strings.Builder
	buf.WriteString(skillSnapshotHeader)

	first := true
	for _, input := range cfg.Inputs {
		for _, locale := range cfg.Locales {
			if !first {
				buf.WriteString("\n---\n\n")
			}
			first = false

			if err := appendSkillSnapshotSection(&buf, repoRoot, locale, input); err != nil {
				return err
			}
		}
	}

	return writeSkillSnapshot(repoRoot, cfg.OutputPath, buf.String())
}

// appendSkillSnapshotSection reads docs/core/<locale>/<input> (relative to
// repoRoot) and appends its `<!-- Source: ... -->`-labeled, link-stripped
// content to buf.
func appendSkillSnapshotSection(buf *strings.Builder, repoRoot, locale, input string) error {
	relPath := filepath.Join("docs", "core", locale, filepath.FromSlash(input))
	content, err := os.ReadFile(filepath.Join(repoRoot, relPath)) //nolint:gosec // G304: repo-relative path from a declared, committed config list
	if err != nil {
		return fmt.Errorf("skill snapshot: reading %s: %w", relPath, err)
	}

	fmt.Fprintf(buf, "<!-- Source: %s -->\n\n", filepath.ToSlash(relPath))
	buf.WriteString(stripRelativeMarkdownLinks(string(content)))
	if len(content) == 0 || content[len(content)-1] != '\n' {
		buf.WriteString("\n")
	}
	return nil
}

func writeSkillSnapshot(repoRoot, outputPath, body string) error {
	fullPath := filepath.Join(repoRoot, filepath.FromSlash(outputPath))
	if err := os.MkdirAll(filepath.Dir(fullPath), 0o750); err != nil {
		return err
	}
	if err := os.WriteFile(fullPath, []byte(body), 0o644); err != nil { //nolint:gosec // G306: matches writeGeneratedProjection's permissions for other generated artifacts
		return err
	}
	fmt.Printf("generated %s\n", outputPath)
	return nil
}

var skillSnapshotMarkdownLink = regexp.MustCompile(`\[([^\]]*)\]\(([^)]+)\)`)

// stripRelativeMarkdownLinks replaces `[label](relative/path.md)` with
// plain `label`, leaving external (http/https/mailto) links untouched.
// Source docs live several directories apart under docs/core/<locale>/,
// so a relative link that resolves correctly there does not resolve once
// flattened into this single bundled file — and TestSkillContractLinksResolve
// (tests/fixtures/skill_contract_links_test.go) enforces that every link
// under skills/ actually resolves. Rewriting the target instead of
// stripping it isn't viable either: the bundle must stay usable standalone
// (ADR-014), so it can't point back at docs/core/ paths that won't exist
// once the skill package is copied outside this repo.
func stripRelativeMarkdownLinks(content string) string {
	return skillSnapshotMarkdownLink.ReplaceAllStringFunc(content, func(match string) string {
		groups := skillSnapshotMarkdownLink.FindStringSubmatch(match)
		label, target := groups[1], groups[2]
		if strings.HasPrefix(target, "http://") || strings.HasPrefix(target, "https://") || strings.HasPrefix(target, "mailto:") {
			return match
		}
		return label
	})
}
